version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - "3306:3306"
    volumes: 
      - ./data:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: sistemaarmada
      MYSQL_USER: sistemaarmada
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_NAME: mysql

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    tty: true
    container_name: php
    ports: 
      - "80:80"
    environment: 
      SERVICE_NAME: php
    depends_on: 
      - mysql
